// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Models.MvcContext;
using MySql.Data.EntityFrameworkCore.Storage.Internal;
using System;

namespace vertivina.Migrations
{
    [DbContext(typeof(MvcContext))]
    [Migration("20181101222157_MascotaAdopcion")]
    partial class MascotaAdopcion
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.3-rtm-10026");

            modelBuilder.Entity("vertivina.Models.Cita", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Direccion");

                    b.Property<string>("Doctor");

                    b.Property<DateTime>("Fecha");

                    b.Property<string>("Hora");

                    b.Property<string>("Mascota")
                        .IsRequired();

                    b.Property<string>("Nombre")
                        .IsRequired();

                    b.Property<int>("Telefono");

                    b.Property<string>("TipoCita");

                    b.Property<string>("TipoMascota");

                    b.Property<string>("TipoTelefono")
                        .IsRequired();

                    b.HasKey("ID");

                    b.ToTable("Cita");
                });

            modelBuilder.Entity("vertivina.Models.Contacto", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Apellido")
                        .IsRequired();

                    b.Property<string>("Direccion")
                        .IsRequired();

                    b.Property<string>("Email")
                        .IsRequired();

                    b.Property<string>("Mensaje")
                        .IsRequired();

                    b.Property<string>("Nombre")
                        .IsRequired();

                    b.Property<int>("Telefono");

                    b.HasKey("ID");

                    b.ToTable("Contacto");
                });

            modelBuilder.Entity("vertivina.Models.Faq", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("contactoNombre")
                        .IsRequired();

                    b.Property<string>("email")
                        .IsRequired();

                    b.Property<DateTime>("fechaInc");

                    b.Property<string>("motivos");

                    b.Property<string>("msj");

                    b.Property<string>("nombrePersonal");

                    b.Property<string>("respuesta");

                    b.Property<string>("solicito");

                    b.Property<string>("tipo");

                    b.Property<int>("tlf");

                    b.HasKey("ID");

                    b.ToTable("Faq");
                });

            modelBuilder.Entity("vertivina.Models.Mascota", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("nombre")
                        .IsRequired();

                    b.Property<string>("tipoMascota")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Adopcion");
                });

            modelBuilder.Entity("vertivina.Models.Producto", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Nombre");

                    b.Property<double>("Precio");

                    b.Property<int>("Stock");

                    b.Property<string>("TipoProd");

                    b.HasKey("ID");

                    b.ToTable("Producto");
                });

            modelBuilder.Entity("vertivina.Models.Producto2", b =>
                {
                    b.Property<int>("Codigo")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Cantidad");

                    b.Property<string>("Desc");

                    b.Property<DateTime?>("Fecven");

                    b.Property<string>("Nombre");

                    b.Property<double>("Precio");

                    b.Property<string>("Tipo");

                    b.HasKey("Codigo");

                    b.ToTable("Producto2");
                });

            modelBuilder.Entity("vertivina.Models.Servicio", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Celular");

                    b.Property<string>("Email");

                    b.Property<string>("Mensaje");

                    b.Property<string>("Nombre");

                    b.Property<double>("Precio");

                    b.HasKey("ID");

                    b.ToTable("Servicio");
                });
#pragma warning restore 612, 618
        }
    }
}
